data/newsletter/Issue-181.markdown

Hi! Since I don't have push access to the new repo I am sending this as a PR. :)

Add a CFP issue

---

data/newsletter/issue-212.markdown

Weekly Update and Multiple Components is hosted on Matthew Pickering's blog, but was written by Fendor
Sorry about that weird extra diff with the ö --- I edited this in the GitHub web editor, it seems to have thrown that in for free

Fix author entry

---

data/newsletter/issue-228.markdown

Hope I got the formatting right?

Add cerveau blog post in Show & tell

---

data/newsletter/issue-233.markdown

Not sure if I added this to the appropriate section.

Add neuron 1.0

---

.gitignore
cabal.project
haskellweekly.cabal
src/lib/HW/Application.hs
src/lib/HW/Handler/Survey.hs
src/lib/HW/Middleware.hs
src/lib/HW/S3.hs
src/lib/HW/Template/Base.hs
src/lib/HW/Template/Episode.hs
src/lib/HW/Template/Index.hs
src/lib/HW/Template/Issue.hs
src/lib/HW/Template/Newsletter.hs
src/lib/HW/Template/Podcast.hs
src/lib/HW/Template/Survey2020.hs
stack.yaml

2020 survey

---

data/newsletter/issue-236.markdown

Hi! I'd like to submit the recently released `wai-feature-flags` library for consideration in the 'show and tell' category!

Add wai-feature-flags library to show-and-tell

---

data/newsletter/issue-245.markdown

Sorry another delayed post, that seems to be missing in previous Haskell Weekly issues.

Add a story about resource pool post by @qnikst

---

data/newsletter/issue-251.markdown

Hi, I wrote a blog post I thought might fit in with the newsletter. I've tried to replicate the example PR linked in the README.
Thanks!

Link to "Writing AWS Lambdas in Haskell" blog post

---

data/newsletter/issue-258.markdown

This PR starts an issue 258 of Haskell Weekly by adding a featured post that motivates algebraic effects in Haskell.

Adds a featured post on algebraic effects

---

data/newsletter/issue-262.markdown

This pull request adds a featured post on errors as values.

Adds a featured post on errors as values

---

data/newsletter/issue-268.markdown

I added the Haskelly by Example video series. Hope this is correct this way. 
Cheers!

Added Haskell by Example video series

---

data/newsletter/issue-270.markdown

Added a featured blog post if that's okay.

Add 'Typed Programs Dont Leak Data to issue 270'

---

data/newsletter/issue-284.markdown

Hello, I would like to submit an article I wrote on pattern matching and guards

Haskell series part 5

---

data/newsletter/issue-288.markdown

Hello, I would like to submit an article I wrote on high order functions.

Haskell series part 6

---

data/newsletter/issue-289.markdown

Add a link to my new blog post on "How To Use a Record Field Name Within a Haskell Module Twice" for beginners.

Add featured post entry

---

data/newsletter/issue-291.markdown

Hello, I would like to submit an article I wrote on map/filter/foldl and function composition.

Haskell Series part 7

---

data/newsletter/issue-298.markdown

Hello, I would like to submit an article I wrote on IO.

Haskell Series part 8

---

data/newsletter/issue-299.markdown

Hello, I would like to submit an article I wrote on modules and exceptions.

Haskell Series part 9

---

data/newsletter/issue-300.markdown

Hello, I would like to submit my final article I wrote on Haskell for beginners about data types and `Maybe`.

Haskell Series part 10

---

data/newsletter/issue-314.markdown

@hasufell What do you think of this wording?
Fixes #122

Add play-haskell to 314

---

data/newsletter/issue-187.markdown
data/newsletter/issue-203.markdown
data/newsletter/issue-208.markdown
data/newsletter/issue-222.markdown
data/newsletter/issue-228.markdown
data/newsletter/issue-233.markdown
data/newsletter/issue-259.markdown
data/newsletter/issue-261.markdown

Most of them are broken due to the neuron -> emanote move. This PR fixes it.

Update links to my articles

---

data/newsletter/issue-326.markdown

add cabal-hoogle to issue 326

---

data/newsletter/issue-326.markdown

Add type-signature to issue 326

---

data/newsletter/issue-328.markdown

issue-328: cfp: cabal deepsubsumption support

---

data/newsletter/issue-330.markdown

Add Ema 0.8 release blog post

---

data/newsletter/issue-330.markdown

I would like to share with you a small project that I have prepared in a blogpost-like style. It deals with stack safety in PureScript through a simple example, trying to be brief and entertaining.

Add blogpost "Implementing array reverse in PureScript"

---

data/newsletter/issue-345.markdown

Issue 345: Add "The unreasonable effectiveness of polymorphic records" by Clément Delafargue

---

data/newsletter/issue-353.markdown

Hey @tfausak it's been a while since I contributed anything to the newsletter, so I thought I'd suggest a blog post that I wrote a couple of weeks ago. It's merely a suggestion, so feel free to reject the PR if you don't think it'll be interesting for the audience.

Add "Fail with class" blog post to the 353rd issue of the newsletter

---

.github/workflows/ci.yaml

https://discourse.haskell.org/t/incident-github-actions-ci-failure-ghcup/5761

Fix Ci build

---

data/newsletter/issue-355.markdown

Add Haskell Playground ticket to issue #355

---

data/newsletter/issue-355.markdown

Add "A concise introduction to generics-sop"

---

data/newsletter/issue-355.markdown

Closes https://github.com/haskellweekly/haskellweekly/issues/165#issuecomment-1430197822

featured: add 'The hakyll-nix-template Tutorial'

---

data/newsletter/issue-356.markdown

It seems strange to me to post text written half of the year ago to newsletter. So let there be the new one.
I'm absolutely ok if you decide to decline this PR for now and publish previous chapter.

Add more recent post from platonic Hask overview to newsletter

---

data/newsletter/issue-357.markdown

Add post on Bellroy's technology stack

---

data/newsletter/issue-357.markdown

Each one comes in the form of a video and an article, which are cross-linked. I don't know how to mention this fact better than a note in parenthesis, I hope this works and makes sense

Suggest content for this week

---

data/newsletter/issue-359.markdown

:facepalm: forgot to do this earlier in the week

Issue 359 - Haskell Developer @ Bellroy

---

data/newsletter/issue-360.markdown

Hello @tfausak! 
Please kindly review and see if this is fit for the next newsletter.
Thanks!

add featured: State Monad: a bit of currying goes a long way

---

data/newsletter/issue-360.markdown

I had a rough time with bare GHCup on macOS, so I documented what I did, and I hope this can help others!

featured: add 'One does not simply use GHCup on macOS M1'

---

data/newsletter/issue-365.markdown

Hi there! Got a couple of CFP issues here.

Add CFP issues

---

data/newsletter/issue-371.markdown

[CodeCrafters](https://codecrafters.io) [`Build your own grep`](https://app.codecrafters.io/courses/grep?track=haskell) challenge now has Haskell support :)

Add CodeCrafters new grep + haskell challenge

---

data/newsletter/issue-380.markdown

feat: Add tree-sitter-haskell speedup article to issue 380

---

data/newsletter/issue-385.markdown

Add issue 385, and add Bellroy post about open source

---

.github/workflows/ci.yaml

- #232 
- #233 
- #234 
- #235

Upgrade workflow actions

---

.github/workflows/ci.yaml

Upgrade artifact actions

---

.github/workflows/ci.yaml

Fix Fly tag

---

data/newsletter/2024/issue-428.markdown

issue 428: Add "Servant on AWS Lambda"

---

source/library/HW/Template/Podcast.hs

Remove Google Podcasts button

---

source/library/HW/Worker.hs

Thanks @puffnfresh for #351! 
Tested locally:

Link to issue from email

---

source/library/HW/Worker.hs

Fixes #350. 
This PR makes the campaigns automatically send 15 minutes after being created. It's a bit strange that you have to create the campaign with `send_at` set and then change its status, but that's what listmonk's API demands. Otherwise it's created as a draft scheduled to be sent; but of course drafts aren't sent. And you can't set the status of a campaign when creating it.

Automatically schedule campaigns

---

data/newsletter/2024/issue-437.markdown

I meant to include this before today's issue was sent out but I forgot. I'm adding it now so that anyone reading today's issue on the web will see the ad.

Add Unison Forall ad

---

data/newsletter/2019/issue-174.markdown
data/newsletter/2020/issue-193.markdown
data/newsletter/2020/issue-197.markdown
data/newsletter/2020/issue-207.markdown
data/newsletter/2020/issue-240.markdown
data/newsletter/2020/issue-243.markdown

Thanks again for featuring my posts!
I'm moving TLD and I'd be super grateful if you could merge this one 🙏

Fix links to odone.me

---

.github/workflows/ci.yaml

Add comment about pinned Cabal version
